-- NEW: profile lifecycle + recommendation consistency fields
ALTER TYPE "ProfileStatus" ADD VALUE IF NOT EXISTS 'PROCESSING';
ALTER TYPE "ProfileStatus" ADD VALUE IF NOT EXISTS 'COMPLETED';
ALTER TYPE "ProfileStatus" ADD VALUE IF NOT EXISTS 'FAILED';
ALTER TYPE "ProfileStatus" ADD VALUE IF NOT EXISTS 'REVIEW_NEEDED';

ALTER TABLE "hiringProfile"
ADD COLUMN IF NOT EXISTS "fileHash" TEXT,
ADD COLUMN IF NOT EXISTS "recommendationBreakdown" JSONB,
ADD COLUMN IF NOT EXISTS "processingTimeMs" INTEGER,
ADD COLUMN IF NOT EXISTS "matchedSkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "missingSkills" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN IF NOT EXISTS "llmStartedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "llmCompletedAt" TIMESTAMP(3),
ADD COLUMN IF NOT EXISTS "tokenUsage" JSONB,
ADD COLUMN IF NOT EXISTS "errorMessage" TEXT,
ADD COLUMN IF NOT EXISTS "retryCount" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

CREATE INDEX IF NOT EXISTS "hiringProfile_openingId_fileHash_idx"
ON "hiringProfile"("openingId", "fileHash");
